### ISSUE TITLE
Install error IOS

### ISSUE THREAD

**Issue by dreamer296** [cometchat-go/ionic-chat-sdk-demo#2]
hi. How can I install the plugin with this error?
Please help. thanks

![error install plugin ios](https://user-images.githubusercontent.com/17842563/41757417-26d30800-760c-11e8-9a6e-bea9bf00c9d8.png)

**Comment by trungnguyenPG** [comment]
me too. please help us. thank you very much!

**Comment by adityagokula2210** [comment]
It seems that Cocoapods is not set up for the iOS project. Please navigate to the platforms/ios folder and run the **pod update** command. 
That should fix the problem.

**Comment by trungnguyenPG** [comment]
@adityagokula2210  thanks you. but there is a another error.
i initialize with my site url, api key , license key but the response  returned is always "connect error"?
how can i solved it?

**Comment by victorescamillan** [comment]
Hello! How can I solve this issue? After downloading I change the bundle identifier to run on my device since the existing one is not working. 
![config_xml](https://user-images.githubusercontent.com/10216357/42010541-be31d5a0-7ac1-11e8-83bb-26b3311e7be6.jpg)

**Comment by adityagokula2210** [comment]
As mentioned earlier,

It seems that Cocoapods is not set up for the iOS project. Please navigate to the platforms/ios folder and run the pod update command.

This has already been resolved. If you still need assistance, please contact us at https://www.cometchat.com/contact-support
