### ISSUE TITLE
GoogleService-Info.plist

### ISSUE THREAD

**Issue by victorescamillan** [cometchat-go/ionic-chat-sdk-demo#3]
Hello! How can I solve this issue? After downloading I change the bundle identifier to run on my device since the existing one is not working.
I also try to create new app in firebase that match the bundle identifier that I used in my app but suddenly I can't make the chat working.

![config_xml](https://user-images.githubusercontent.com/10216357/42010661-4c9fcc3e-7ac2-11e8-9a84-85c8d2d0beba.jpg)

**Comment by jeetkapadia** [comment]
This is just a warning, which is auto-generated by the firebase incase when the App bundle Identifier does not match with the bundle identifier present in the GoogleService-Info.plist. It doesn't affect your project at all. Incase if you have added the new GoogleService-Info.plist file which contains the App Identifier of your App then clean your project, clear your derived data, and then try running your App.
