### ISSUE TITLE
Problem with incoming call

### ISSUE THREAD

**Issue by azebac** [cometchat-go/ionic-chat-sdk-demo#6]
When someone from the web (or other mobile) calls and the chat is not open in the receiver the call doesnt open until the caller cancels the call for example:

SuperHero4: Web Client
SuperHero1: Mobile Client

SuperHero4 calls SuperHero1 without previous chat, SuperHero1 wont see the call.

Both clients were using the examples from the page.

**Comment by jitvarpatil** [comment]
Hello,
For this functionality to work push notifications functionality needs to be configured in your app. You can refer the following documentation to configure push notifications in your app.

https://developer.cometchat.com/docs/cordova-push-notifications

If you have push notification integrated into your app and still facing this issue you can schedule a session at the following link:

https://www.cometchat.com/schedule-session/
