### ISSUE TITLE
"Error in Success callbackId: CCCometChat1199030706 : TypeError: Cannot read property 'fcm' of undefined"

### ISSUE THREAD

**Issue by binita12345** [cometchat-go/ionic-chat-sdk-demo#9]
How can I solve this error?

I am using same code for push notification in comet chat. when open comet chat window, getting **"Error in Success callbackId: CCCometChat1199030706 : TypeError: Cannot read property 'fcm' of undefined"**

**Comment by mehtanishant** [comment]
Hi @binita12345,

We are checking the mentioned issue at our end. It would be very helpful if you can let us know for which platform(Android/iOS) you are facing the issue.

You can also schedule a remote session with us. Kindly use the following link to schedule a session:

https://www.cometchat.com/schedule-session

Thank you.

**Comment by pushpsenairekar2911** [comment]
Hi @binita12345,

We hope your day is going well. 

Kindly use the below link to download the fcm plugin and replace this folder with the fcm plugin folder inside your project directory.

https://bit.ly/2Tct6g3

If you still face any issues then schedule a session with us using below link:

https://www.cometchat.com/schedule-session

Do not hesitate to contact us if you have any queries/concerns. We'll be glad to assist you.

**Comment by binita12345** [comment]
> Hi @binita12345,
> 
> We are checking the mentioned issue at our end. It would be very helpful if you can let us know for which platform(Android/iOS) you are facing the issue.
> 
> You can also schedule a remote session with us. Kindly use the following link to schedule a session:
> 
> https://www.cometchat.com/schedule-session
> 
> Thank you.

I am facing this issue in Android Platform.
